server:
    port: 8080

database:
    host: ...postresql-host...
    port: 5432
    user: ...user...
    password: ...password...
    dbname: ...dbname...

auth:
    jwt_secret: ...your-secret-key...
    secure: false # https only cookies
    bcrypt_cost: 13
    access_expiration: 15
    refresh_expiration: 20160 # two weeks
